name: build and test

on:
  push:
    branches: [main]

  pull_request:
    branches: ['**']

  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: submodule update??
        run: |
          git submodule update --init
      - name: build
        run: |
          mkdir build
          cd build
          cmake ..
          make
